### ISSUE TITLE
1장, 2장 스터디

### ISSUE THREAD

**Issue by boring-km** [Just-Android-Compose-Study/JetpackComposeStudy#2]
## TODO

- [ ] 교재 내용 정리
- [ ] 샘플 코드 작성하기
- [ ] 테스트 코드 작성하기 (선택)
